# Generated by Django 4.0.5 on 2022-06-20 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffeSalary',
            new_name='StaffSalary',
        ),
    ]
