# Generated by Django 4.0.5 on 2022-06-22 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistapp', '0002_rename_staffesalary_staffsalary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='id',
            new_name='bill_id',
        ),
        migrations.RenameField(
            model_name='billdetails',
            old_name='id',
            new_name='billdetail_id',
        ),
        migrations.RenameField(
            model_name='chemist',
            old_name='id',
            new_name='chemist_id',
        ),
        migrations.RenameField(
            model_name='chemistaccount',
            old_name='id',
            new_name='account_id',
        ),
        migrations.RenameField(
            model_name='chemistaccount',
            old_name='company_id',
            new_name='chemist_id',
        ),
        migrations.RenameField(
            model_name='chemistbank',
            old_name='id',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='customerrequest',
            old_name='id',
            new_name='request_id',
        ),
        migrations.RenameField(
            model_name='medicaldetails',
            old_name='id',
            new_name='details_id',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='company_id',
            new_name='chemist_id',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='id',
            new_name='medicine_id',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='id',
            new_name='staff_id',
        ),
        migrations.RenameField(
            model_name='staffbank',
            old_name='id',
            new_name='bank_id',
        ),
        migrations.RenameField(
            model_name='staffsalary',
            old_name='id',
            new_name='salary_id',
        ),
    ]
